### ISSUE TITLE
Error meet after npm install

### ISSUE THREAD

**Issue by lizhiyu-me** [MrKylinGithub/OpenTGX#2]
MacOS 13.3.1
Nodejs v18.15.0
Npm 9.5.0
---
below is the complete error log
```
> frontend@3.4.2 postinstall
> cd ../tgx-metaverse-server && npm i && npm run sync


up to date in 1s

34 packages are looking for funding
  run `npm fund` for details

> backend@0.1.0 sync
> tsrpc-cli sync

[Error: ENOENT: no such file or directory, stat '/Users/steffan/Study/OpenTGX/tgx-metaverse-online/tgx-metaverse-client/assets/module_metaverse/scripts/shared'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/Users/steffan/Study/OpenTGX/tgx-metaverse-online/tgx-metaverse-client/assets/module_metaverse/scripts/shared'
}
npm ERR! code 1
npm ERR! path /Users/steffan/Study/OpenTGX/tgx-metaverse-online/tgx-metaverse-client
npm ERR! command failed
npm ERR! command sh -c cd ../tgx-metaverse-server && npm i && npm run sync
```

**Comment by MrKylinGithub** [comment]
sorry for the lack of documentations.
it's easy to use with the following steps.

for server side. locate into tgx-metaverse-server folder, then execute the following instructions.
```
//install tsrpc
npm install
//run master server
npm run dev:master
//open another terminal and run world server
npm run dev:world
```

for client side.
first, locate into `tgx-metaverse-client` folder and run `npm install` to install tsrpc stuff.

second ,add tgx-metaverse-client to Cocos Dashboard

finally, open tgx-metaverse-client project using the corresponding Cocos Creator version( need to be installed first).

choose 'start' as the first scene, then click play button on the top of the scene editor to run.
